# Generated by Django 4.1 on 2022-09-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlujoDeTarea',
            fields=[
                ('id_flujo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_flujo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'flujo_de_tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_problema', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=500)),
                ('plazo_solucion', models.DateField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id_semaforo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado_semaforo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'semaforo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tarea', models.CharField(max_length=500)),
                ('descripcion_tarea', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('avance', models.CharField(max_length=500)),
                ('tarea_sub_id_tarea_sub', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'tarea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareaSub',
            fields=[
                ('id_tarea_sub', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tarea_sub', models.CharField(max_length=500)),
                ('descripcion_tarea_sub', models.CharField(max_length=500)),
                ('fecha_inicio_sub', models.DateField()),
                ('fecha_termino_sub', models.DateField()),
                ('avance_tarea_sub', models.CharField(max_length=500)),
                ('tarea_id_tarea', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'tarea_sub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadInterna',
            fields=[
                ('id_unidad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'unidad_interna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=500)),
                ('contraseña_usuario', models.CharField(max_length=500)),
                ('correo_usuario', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
